### PR TITLE
Add red Sentry Buster materials

### PR DESCRIPTION
**Pull request by sticks-stuff**
I've added the red sentry buster material created by sigsegv (https://gamebanana.com/skins/140008). While a Red Sentry Buster will never be seen by default, it is useful for community servers that use various plugins to spawn/turn a player into a sentry buster.

### CODE REVIEW

**Comment by agrastiOs** [comment]
Not a good idea. The UTF2VFP had it, but after some playtesting we noticed that in some custom MvM missions, the are Red Sentry Busters for balance reasons, which with their red legs and blue body stick out like a sore thumb. The only way this could work if a red body texture was made, and even then, it doesn't seem like mission creators intend to have these look noticeably Red. 

Also, sigsegv would need to sign the CLA for this.

**Comment by DrCactusTF2** [comment]
There are red busters in some custom potato.tf missions
https://gamebanana.com/skins/165605
This might work better

**Comment by sticks-stuff** [comment]
>  their red legs and blue body stick out like a sore thumb. The only way this could work if a red body texture was made, and even then, it doesn't seem like mission creators intend to have these look noticeably Red.

I'm fairly certain that unless somethings gone wrong, the sentry buster should just use the red giant demobot textures for its legs.

**Comment by agrastiOs** [comment]
Yep, that is how it does work, but the blue body stays as there no red material for sentry buster, so it's super jarring.

**Comment by sticks-stuff** [comment]
This PR adds a red material for the sentry buster though?

**Comment by agrastiOs** [comment]
It does only for the legs, as a red body texture does not exist.

**Comment by agrastiOs** [comment]
Update: after a few talks with the potato.tf community, it seems like they would prefer the red sentry buster to appear as so, as a few servers (not all) have a plug-in to replace the blu sentry busters with red, custom textures.

I can make a red sentry buster texture and bring it back to the sentry buster model in UTF2VFP, then port it over to here.

**Comment by agrastiOs** [comment]
Question: what is that .vtf that you posted, and where did it come from? Sigsegv doesn't have it in their mod. Also, you didn't bring in the model changes from his pack, which would add the red legs, making the pull request not working as intended. This could actually happen if I do what I mentioned in the previous comment.

Unless you were wanting just to add the red .vmt and .vtf (which I presume you made and that it is indeed the red texture for the Buster's body), allowing these stray files to be picked up only by a community plug-in to use in forcing a texture change? Putting in stray assets for community server plugins to use doesn't sound like a good idea.

**Comment by sticks-stuff** [comment]
You're correct that I am an idiot and this doesn't work because I didn't import the model changes. I'm still an idiot as well because I can't even import a fixed model because it would conflict with the model currently in this repo. As such I'm closing.

**Comment by agrastiOs** [comment]
Yeah, but where did you get the red texture from? Maybe this perhaps? https://gamebanana.com/skins/165605

**Comment by sticks-stuff** [comment]
https://gamebanana.com/skins/140008

**Comment by agrastiOs** [comment]
Definitely not that one, I checked the .vpk

This has the texture, it seems https://gamebanana.com/skins/140866

**Comment by sticks-stuff** [comment]
Ah, my bad

**Comment by agrastiOs** [comment]
@DrCactusTF2 looking at the original place where that sentry buster texture was, looks like it was uploaded by sigsegv, but made by someone known as "FissionMetroid101"

**Pull request closed without merging**
