### PR TITLE
Update link to repo

### PR DESCRIPTION
**Pull request by micwoj92**

### CODE REVIEW

**Comment by micwoj92** [comment]
Thank you @CLAassistant.

**Comment by mastercoms** [comment]
I think this current link is more future proof, since it redirects to the current repo and also will be a direct link if the repo gets renamed to team-comtress-2 again. Thoughts?

**Comment by micwoj92** [comment]
This one should also redirect in case of future name changes.

**Comment by mastercoms** [comment]
The current link was future proof for what is the present now, and is still future proof. I'd go with that track record than some new change which is only anticipating a future outcome.

**Pull request closed without merging**
